### ISSUE TITLE
Bot shows up in chat but no /commands

### ISSUE THREAD

**Issue by romtecmax** [ThePoShWolf/azfunc-pwsh-discord-bot#1]
Hi there, thanks for sharing this repo

I'm trying to get it to work, and everthing works fine, the bot shows up as online in my server and i'm able to save the interactions url - BUT i can not use any /commands, not even /hello.

what might be the issue here?

**Comment by ThePoShWolf** [comment]
Can you explain what you mean when you say that you can't use any slash commands?

**Comment by romtecmax** [comment]
I found the problem:
I forgot to actually add the commands as described in the last section of the readme. Shame on me!

**Comment by ThePoShWolf** [comment]
Ha! That'll do it. I'm glad you figured it out!

**Comment by romtecmax** [comment]
yep thanks for the prompt response anyways!
